-- Core durable storage for the Netlify migration.
-- Run this in the Supabase SQL editor before enabling production functions.

create extension if not exists pgcrypto;

create table if not exists public.teams (
  id text primary key,
  registration_number text not null unique,
  team_name text not null,
  leader_email text not null,
  access_password_hash text not null,
  preferred_track text not null,
  status text not null default 'Confirmed',
  created_at timestamptz not null default now(),
  project_submitted boolean not null default false,
  payment_utr text,
  payment_status text not null default 'Pending',
  payment_screenshot_path text
);

create table if not exists public.participants (
  id text primary key,
  team_id text not null references public.teams(id) on delete cascade,
  full_name text not null,
  college text not null,
  department text not null,
  semester text not null,
  email text not null,
  phone text not null default '',
  usn text not null default '',
  gender text not null default '',
  github_url text,
  linkedin_url text,
  role text not null,
  accommodation_required boolean not null default false,
  emergency_contact text not null default '',
  checked_in boolean not null default false,
  check_in_time timestamptz,
  food_coupons_claimed jsonb not null default '{}'::jsonb
);

create index if not exists participants_team_id_idx on public.participants(team_id);
create index if not exists participants_email_idx on public.participants(lower(email));

create table if not exists public.registration_backup_rows (
  id bigint generated by default as identity primary key,
  registration_timestamp timestamptz not null,
  team_id text not null,
  registration_number text not null,
  team_name text not null,
  track text not null,
  participant_id text not null,
  participant_name text not null,
  role text not null,
  email text not null,
  phone text not null default '',
  usn text not null default '',
  college text not null default '',
  department text not null default '',
  semester text not null default '',
  gender text not null default '',
  github_url text,
  linkedin_url text,
  accommodation_required boolean not null default false,
  emergency_contact text not null default '',
  payment_utr text,
  payment_status text,
  team_status text not null
);

alter table public.teams enable row level security;
alter table public.participants enable row level security;
alter table public.registration_backup_rows enable row level security;

-- Netlify Functions use SUPABASE_SERVICE_ROLE_KEY server-side. No service-role
-- key belongs in React or in a VITE_* environment variable.

insert into storage.buckets (id, name, public)
values ('payment-screenshots', 'payment-screenshots', false)
on conflict (id) do nothing;